accounts/urls.py
from distutils.log import Log
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView
from . import views

app_name='accounts'

urlpatterns=[
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('signup/',views.SignupView.as_view(),name='signup'),
    
]

app/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.HelloClass.as_view(),name='index'),
    path('list/',views.AppList.as_view(),name='app-list'),
    path('detail/<int:pk>/',views.AppDetail.as_view(),name='app-detail'),
    path('create/',views.AppCreate.as_view(),name='app-create'),
    path('delete/<int:pk>',views.AppDelete.as_view(),name='app-delete'),
    path('update/<int:pk>',views.AppUpdate.as_view(),name='app-update'),
    

    
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/",include('accounts.urls')),
    path("",include('app.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models

class App(models.Model):
    title=models.CharField(max_length=100)
    text=models.TextField()
    degree=models.CharField(
        max_length=100,
        choices=(('0','0%'),('10','10%'),("20","20%"),("30","30%"),
        ("40","40%"),("50","50%"),("60","60%"),("70","70%"),("80","80%"),
        ("90","90%"),("100","100%"),("120","limit-break"),),
        null=True,
    )
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=('username',)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import SignupForm


# Create your views here.
class SignupView(CreateView):
    model=User
    template_name='accounts/signup.html'
    form_class=SignupForm
    success_url=reverse_lazy('accounts:login')

app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView,CreateView,DeleteView,UpdateView
from app.models import App
from django.urls import reverse_lazy
# Create your views here.
class HelloClass(TemplateView):
    template_name='index.html'

class AppList(ListView):
    template_name='app/app_list.html'
    model=App

class AppDetail(DetailView):
    template_name='app/app_detail.html'
    model=App

class AppCreate(CreateView):
    template_name='app/app_create.html'
    model=App
    fields=('title','text','degree')
    success_url=reverse_lazy('app-list')


class AppDelete(DeleteView):
    template_name='app/app_delete.html'
    model=App
    success_url=reverse_lazy('app-list')

class AppUpdate(UpdateView):
    template_name='app/app_update.html'
    model=App
    fields=('title','text','degree')
    success_url=reverse_lazy('app-list')

accounts/templates/accounts/signup.html
{% extends 'base.html'%}

{%block title%}ユーザー登録{%endblock%}

{%block body%}
<form method="post" >
    {%csrf_token%}
    <div class="form-group">
        <label for="exampleInputEmail1">ユーザーネーム</label>
        <input type="text" name="username" placeholder="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>

    <div class="form-group">
      <label for="exampleInputPassword1">パスワード</label>
      <input type="password" name="password1" placeholder="password" class="form-control" id="exampleInputPassword1">
    </div>

    <div class="form-group">
        <label for="exampleInputPassword2">確認用</label>
        <input type="password" name="password2" placeholder="Please enter the same password again" class="form-control" id="exampleInputPassword2">
    </div>

    <!-- name=password1,password2はUserCreationFormのフィールド名に対応している。 -->


    <small>Please enter a password with at least 8 characters</small><br>
    {%if form.errors%}
    登録できませんでした。確認のうえ、再度入力してください。<br>
    {%endif%}
    <br>
    <button type="submit" class="btn btn-outline-primary float-right">アカウント作成</button>
    
</form>


{%endblock%}

app/templates/app/app_create.html
{% extends 'base.html' %}
{% block title %}create{% endblock title %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="card  mt-5" >
        <div class="card-header" style="width:100%">
            {{form.as_p}} 
        </div>
        <button class="btn btn-outline-primary " type="submit">作成</button>          
    </div> 
</form>
{% endblock body %}

app/templates/app/app_delete.html
{% extends 'base.html' %}
{% block title %}delete{% endblock title%}
{% block body %}
<div class="alert alert-info"  role="alert">
    This page is a "delete-only page". You can delete items displayed here.
</div>
<div class="mx-auto"  style="width:90%">
    <form method="POST">{% csrf_token %}
        <div class="card my-3 mx-auto" style="width:80%">
            <div class="card-body">
              <h2 class="card-title">{{object.title}}</h2>
              <h5 class="card-text">{{object.text}}</5>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">degree:{{object.degree}}</li>
              <li class="list-group-item">user:ユーザーネーム</li>
              <li class="list-group-item">time:時間</li>
            </ul>
            <button type="submit" class="btn btn-outline-danger">Remove「{{object.title}}」</button>
            
          </div>   
    </form>
</div>



{% endblock body%}

app/templates/app/app_detail.html
{% extends 'base.html' %}
{% block title %}detail{% endblock title %}
{% block body %}
<div class="card my-3 mx-auto" style="width:80%">
    <div class="card-body">
      <h2 class="card-title">{{object.title}}</h2>
      <h5 class="card-text">{{object.text}}</5>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">degree:{{object.degree}}</li>
      <li class="list-group-item">user:ユーザーネーム</li>
      <li class="list-group-item">time:時間</li>
    </ul>
    <div class="card-body">
        <a href="{% url 'app-update' object.pk %}" class="btn btn-outline-primary float-right mx-1">update</a>
        <a href="{% url 'app-delete' object.pk %}" class="btn btn-outline-danger float-right mx-1">delete</a>
        <a href="{% url 'app-list' %}" class="btn btn-outline-info float-right mx-1">←list</a>
    </div>
  </div>

  
{% endblock body %}

app/templates/app/app_list.html
{% extends 'base.html' %}
{% block title %}list{% endblock title %}
{% block body %}
<div class="row mx-auto" style="width:90%">
    {% for i in object_list%}
    <div class="list-group">
    <a href="{% url 'app-detail' i.pk %}" class="list-group-item list-group-item-action my-2" style="display:block">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{i.title}}</h5>
          <small class="text-muted">day~~</small>
        </div>
        <p class="mb-1 text-muted">{{i.text|truncatechars:15}}</p>
        <small class="text-muted">コメント</small>
    </a>
    </div>
    {%endfor%}
</div>

{% endblock body %}
 

app/templates/app/app_update.html
{% extends 'base.html' %}
{% block title %}update{% endblock title %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="card  mt-5" >
        <div class="card-header" style="width:100%">
            {{form.as_p}} 
        </div>
        <button class="btn btn-outline-primary " type="submit">更新</button>          
    </div> 
</form>
{% endblock body %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <div class="row mx-auto" style="width:100%">        
            <nav class="navbar navbar-dark bg-dark">
            {% if request.user.is_authenticated %}
              <a href="{%url 'index'%}" class="col-2"><i class="fa-solid fa-house fa-3x" style="color: rgb(0, 191, 255)"></i></a>    
              <a href="{%url 'app-list'%}" class="col-2"><i class="fa-solid fa-list fa-3x" style="color: rgb(0, 191, 255)"></i></a>
              <a href="{%url 'app-create'%}"class="col-2"><i class="fa-solid fa-plus fa-3x" style="color: rgb(0, 191, 255)"></i></a> 
              <a href="#"class="col-2"><i class="fa-solid fa-user fa-3x" style="color: rgb(0, 191, 255)"></i></a> 
              <a  href="{% url 'accounts:logout'%}"><i class="fa-solid fa-person-walking-arrow-right fa-3x"></i></a>
            {% else %}
              <a  href="{% url 'accounts:login'%}"><i class="fa-solid fa-right-to-bracket fa-3x"></i></a>
              <a  href="{% url 'accounts:signup' %}"><i class="fa-solid fa-user-check fa-3x"></i></a>

            {% endif %} 
            </nav>
  </div>
{% block body %}{% endblock body %}
</body>
</html>

templates/index.html
{%extends 'base.html'%}

{%block title%}
トップぺージ
{%endblock title%}


{% block body%}
<h1>morning!!!</h1> 
{%endblock body %}
    